### ISSUE TITLE
Plugin does not work in version 1.21

### ISSUE THREAD

**Issue by GoPoux4** [WhiteXero/ShowIt#4]
Command `!!show` and `!!skull <player>` fail in 1.21, maybe due to changes of the data component.

<img width="329" alt="截屏2024-07-01 11 01 06" src="https://github.com/WhiteXero/ShowIt/assets/56778898/7dce9325-f857-44bd-aa6f-d1b7e889967b">

Entering `!!skull <player>` will display infos but with no command executed.

**Comment by WhiteXero** [comment]
Will fix this in few days.
ty <3

________________________________
发件人: GoPoux4 ***@***.***>
发送时间: 2024年7月1日 11:11
收件人: WhiteXero/ShowIt ***@***.***>
抄送: Subscribed ***@***.***>
主题: [WhiteXero/ShowIt] Plugin does not work in version 1.21 (Issue #4)


Command !!show and !!skull <player> fail in 1.21, maybe due to changes of the data component.

2024-07-01.11.01.06.png (view on web)<https://github.com/WhiteXero/ShowIt/assets/56778898/7dce9325-f857-44bd-aa6f-d1b7e889967b>

Entering !!skull <player> will display infos but with no command executed.

―

**Comment by WhiteXero** [comment]
i will make a reloaded version for different version of minecraft.
